### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by PreHeX** [NinjaCheetah/NUSGet#4]
I cant launch the programm Windows Defender keeps removing the .exe and saying "It could harm ur System and is not posible to launch"

How can i prevent the System to remove the application?

**Comment by NinjaCheetah** [comment]
You'll have to launch Defender and allow it from the virus protection menu. It should also give you a notification when it blocks it from running or deletes it, and clicking that notification should take you directly where you have to go to allow it.

You'll can also add an exclusion before trying to run it as described [here](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#ID0EBF=Windows_11).

**Comment by NinjaCheetah** [comment]
Marking as completed since it's been about a week now. Feel free to reopen if you're still having trouble.
